#!/bin/sh
module="gpio"
device="gpio"
mode="664"

/sbin/insmod ./$module.ko $* || exit 1

rm -f /dev/${device}[0-1]

major=$(awk '$2=="gpio" {print $1}' /proc/devices)

mknod /dev/${device}0 c $major 0
mknod /dev/${device}1 c $major 1


